agents:
  queue: macos

steps:
  - label: ":pod: test normal cocoapods"
    commands:
      - "bundle install"
      - "bundle exec fastlane test_normal_pods"

  - label: ":pod: test clean cocoapods" 
    commands:
      - "bundle install"
      - "bundle exec fastlane test_clean_pods"