agents:
  queue: macos

cache:
  paths:
    - ".cache/bundler"
  name: "gems"

steps:
  - label: ":ruby: install dependencies"
    key: install-dependencies-ruby
    command: .buildkite/scripts/install-dependencies.sh

  - label: ":macos: build"
    key: build-apple
    command: .buildkite/scripts/build.sh
    depends_on:
      - install-dependencies-ruby

  - label: ":lock: build with code signing"
    key: build-apple-signed
    depends_on:
      - install-dependencies-ruby
    secrets:
      - CERT_BASE64
      - CERT_PASS
      - PROFILE_BASE64
      - DEVELOPMENT_TEAM
    plugins:
      - tadhgo/apple-signing-setup#main:
          certificate:
            base64_env: CERT_BASE64
            password_env: CERT_PASS
          provisioning_profiles:
            - file_path: /tmp/FlappyKiteTestDev.mobileprovision
          prep_command: |
            echo "$${PROFILE_BASE64}" | base64 -d > /tmp/FlappyKiteTestDev.mobileprovision
            bundle config set path '.cache/bundler'
            bundle install
          command: bundle exec fastlane build

  - label: ":macos: test"
    command: .buildkite/scripts/test.sh
    depends_on:
      - build-apple
    artifact_paths:
      - "fastlane/test_output/report.junit"

  - label: ":macos: :camera: screenshots"
    command: .buildkite/scripts/screenshots.sh
    depends_on:
      - build-apple-signed
      - bazel-test
    artifact_paths:
      - "screenshots/**/*.png"

  - label: ":bazel: build"
    key: bazel-build
    command: |
      bazelisk build //FlappyKite:FlappyKite
    cache:
      paths:
        - ".cache"
      size: "20g"
      name: "bazel"

  - label: ":bazel: test"
    key: bazel-test
    depends_on:
      - bazel-build
    command: |
      bazelisk test //FlappyKiteTests:FlappyKiteTests //FlappyKiteUITests:FlappyKiteUITests
    cache:
      paths:
        - ".cache"
      size: "20g"
      name: "bazel"
