# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    sh('cp ../Config.xcconfig.template ../Config.xcconfig')
  end

  desc 'Build and archive a signed app using fastlane gym'
  lane :build do
    gym(
      scheme: 'FlappyKite',
      export_method: 'development',
      export_team_id: ENV['DEVELOPMENT_TEAM'],
      xcargs: "DEVELOPMENT_TEAM=#{ENV['DEVELOPMENT_TEAM']} CODE_SIGN_STYLE=Manual PROVISIONING_PROFILE_SPECIFIER=com.buildkite.FlappyKite"
    )
  end

  desc 'Run unit and UI tests'
  lane :tests do
    run_tests(
      scheme: 'FlappyKite',
      derived_data_path: './DerivedData',
      devices: ['iPhone 16 (18.6)'],
      ensure_devices_found: true,
      prelaunch_simulator: true,
      code_coverage: true
    )
  end
end
