# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc 'Build and archive a signed app using fastlane gym'
  lane :build do
    gym(
      scheme: 'FlappyKite',
      export_method: 'development',
      team_id: ENV['DEVELOPMENT_TEAM'],
      xcargs: 'CODE_SIGN_STYLE=Manual PROVISIONING_PROFILE_SPECIFIER=FlappyKiteTestDev'
    )
  end

  desc 'Run unit and UI tests'
  lane :tests do
    run_tests(
      scheme: 'FlappyKite',
      derived_data_path: './DerivedData',
      devices: ['iPhone 16 (18.6)'],
      ensure_devices_found: true,
      prelaunch_simulator: true,
      code_coverage: true
    )
  end
end
